services:
  postgres_xbox_profiles_db:
    image: postgres
    container_name: postgres_xbox_profiles_db
    restart: always
    ports:
      - 4457:5432
    env_file:
      - back_end/.env
    volumes:
      - pg_xbox_profiles_db:/var/lib/postgresql/data

  node_xbox_profiles_app:
    container_name: node_xbox_profiles_app
    build: ./back_end
    image: node_xbox_profiles_app_image
    ports:
      - 5000:5000
    depends_on:
      - postgres_xbox_profiles_db
    env_file:
      - back_end/.env

  react_xbox_profiles_app:
    container_name: react_xbox_profiles_app
    build: ./front_end
    image: react_xbox_profiles_app_image
    ports:
      - 3000:3000
    stdin_open: true
    env_file:
      - front_end/.env
    volumes:
      - build_react:/var/www/html

  nginx_xbox_profiles_app:
    container_name: nginx_xbox_profiles_app
    build: ./nginx
    image: nginx_xbox_profiles_app_image
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - postgres_xbox_profiles_db
      - node_xbox_profiles_app
      - react_xbox_profiles_app

volumes:
  pg_xbox_profiles_db:
  build_react:
