on:
  push:
    branches:
      - main
name: Build and Deploy
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create back-end env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_HOST: ${{secrets.POSTGRES_HOST}}
          envkey_POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
          envkey_POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
          envkey_PORT: ${{secrets.PORT}}
          envkey_BCRYPT_SALT: ${{secrets.BCRYPT_SALT}}
          envkey_JWT_TOKEN: ${{secrets.JWT_TOKEN}}
          directory: back_end/
          file_name: .env
          fail_on_empty: true

      - name: Create front-end env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REACT_APP_BASE_URL: ${{secrets.REACT_APP_BASE_URL}}
          directory: front_end/
          file_name: .env
          fail_on_empty: true

      - name: Build
        run: docker compose build && mkdir -p ~ubuntu/actions-runner/_work/Xbox-Profiles/Xbox-Profiles/html

      - name: Run
        run: docker compose down && docker compose up -d

      - name: Update frontend
        run: docker cp react_xbox_profiles_app:/app/build ~ubuntu/actions-runner/_work/Xbox-Profiles/Xbox-Profiles/front_end/ && cp -fR ~ubuntu/actions-runner/_work/Xbox-Profiles/Xbox-Profiles/front_end/build/* ~ubuntu/actions-runner/_work/Xbox-Profiles/Xbox-Profiles/html/ && docker cp ~ubuntu/actions-runner/_work/Xbox-Profiles/Xbox-Profiles/html/ react_xbox_profiles_app:/var/www
